lists/urls.py
from django.conf.urls import url
from lists import views

urlpatterns = [
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
    url(r'^(\d+)/share$', views.share_list, name='share_list'),
    url(r'^users/(.+)/$', views.my_lists, name='my_lists'),
]

superlists/urls.py
from django.conf.urls import include, url

from accounts import urls as accounts_urls
from lists import views as list_views
from lists import urls as list_urls
# we use the import x as y syntax to alias views and urls. This is
# good practice in your top-level urls.py, because it will let us
# import views and urls from multiple apps if we want

urlpatterns = [
    url(r'^$', list_views.home_page, name='home'),
    url(r'^lists/', include(list_urls)),
    url(r'^accounts/', include(accounts_urls)),
]

lists/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models

# Create your models here.


class List(models.Model):
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        blank=True,
        null=True
    )
    shared_with = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='shared_lists'
    )

    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])

    @property
    def name(self):
        return self.item_set.first().text

    @staticmethod
    def create_new(first_item_text, owner=None):
        list_ = List.objects.create(owner=owner)
        Item.objects.create(text=first_item_text, list=list_)
        return list_


class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None)

    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

    def __str__(self):
        return self.text

lists/forms.py
from django import forms
from django.core.exceptions import ValidationError

from lists.models import Item, List


DUPLICATE_ITEM_ERROR = "You've already got this in your list"
EMPTY_ITEM_ERROR = "You can't have an empty list item"


class ItemForm(forms.models.ModelForm):
    # ModelForms do all sorts of smart stuff, like assigning sensible
    # HTML form input types to different types of field, and applying
    # default validation.
    class Meta:
        model = Item
        fields = ('text',)
        # In Meta we specify which model the form is for, and which
        # fields we want it to use.
        widgets = {
            'text': forms.fields.TextInput(attrs={
                'placeholder': 'Enter a to-do item',
                'class': 'form-control input-lg'
            }),
        }
        error_messages = {
            'text': {'required': EMPTY_ITEM_ERROR}
        }


class NewListForm(ItemForm):

    def save(self, owner):
        if owner.is_authenticated:
            return List.create_new(
                first_item_text=self.cleaned_data['text'],
                owner=owner
            )
        else:
            return List.create_new(first_item_text=self.cleaned_data['text'])


class ExistingListItemForm(ItemForm):
    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)


#           Hiding ORM Code Behind Helper Methods
# One of the techniques that emerged from our use of isolated tests
# was the “ORM helper method”.

# Django’s ORM lets you get things done quickly with a reasonably
# readable syntax (it’s certainly much nicer than raw SQL!). But some
# people like to try to minimise the amount of ORM code in the
# application—particularly removing it from the views and forms
# layers.

# One reason is that it makes it much easier to test those layers.
# But another is that it forces us to build helper functions that
# express our domain logic more clearly. Compare:
        # list_ = List()
        # list_.save()
        # item = Item()
        # item.list = list_
        # item.text = self.cleaned_data['text']
        # item.save()
# With:
        # List.create_new(first_item_text=self.cleaned_data['text']
# This applies to read queries as well as write. Imagine something
# like this:
        # Book.objects.filter(in_print=True, pub_date__lte=datetime.
        # today())
# Versus a helper method, like:
        # Book.all_available_books()
# When we build helper functions, we can give them names that express
# what we are doing in terms of the business domain, which can
# actually make our code more legi‐ ble, as well as giving us the
# benefit of keeping all ORM calls at the model layer, and thus
# making our whole application more loosely coupled.

lists/views.py
# Django's MVC, URLs, and View Functions
# Django is structured along a classic Model-View-Controller (MVC)
# pattern. It definitely does have models, but its views are more
# like a controller, and it's the templates that are actually the
# view part, but the general idea is there.

# As with any web server, Django's main job is to decide what to do
# when a user asks for a particular URL on our site. Django's workfow
# goes something like this:
# 1. An HTTP request comes in for a particular URL.
# 2. Django uses some rules to decide which view function should deal
#   with the request (this is referred to as resolving the URL).
# 3. The view function processes the request and returns an HTTP
#   response.

from django.contrib.auth import get_user_model
from django.http import HttpResponse
from django.shortcuts import redirect, render

from lists.forms import ExistingListItemForm, ItemForm, NewListForm
from lists.models import List

User = get_user_model()


def home_page(request):
    # Refactor
    # When we try to improve the code without changing its
    # functionality
    # When refactoring, work on either the code or the tests, but not
    # both at once.
    return render(request, 'home.html', {'form': ItemForm()})
    # Instead of building our own HttpResponse, we now use the Django
    # render function. It takes the request as its first parameter
    # and the name of the template to render. Django will
    # automatically search folders called templates inside any of
    # your apps’ directories. Then it builds an HttpResponse for you,
    # based on the content of the template.
    # Templates are a very powerful feature of Django’s, and their
    # main strength consists of substituting Python variables into
    # HTML text.


def new_list(request):
    form = NewListForm(data=request.POST)
    if form.is_valid():
        list_ = form.save(owner=request.user)
        return redirect(list_)
    return render(request, 'home.html', {'form': form})


def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)
    if request.method == 'POST':
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)
    return render(
        request,
        'list.html',
        {'list': list_, "form": form}
    )


def my_lists(request, email):
    owner = User.objects.get(email=email)
    return render(request, 'my_lists.html', {'owner': owner})


def share_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    list_.shared_with.add(request.POST['sharee'])
    return redirect(list_)


# Our two views are now looking very much like “normal” Django views:
# * they take information from a user’s request,
# * combine it with some custom logic or information from the URL
#    (list_id),
# * pass it to a form for validation and possible saving, and
# * then redirect or render a template.


#   A Decision Point: Whether to Proceed to the Next Layer with a Failing Test

# In order to get this test passing, as it’s written now, we have to
# move down to the model layer. However, it means doing more work
# with a failing test, which is not ideal.

# The alternative is to rewrite the test to make it more isolated
# from the level below, using mocks.

# On the one hand, it’s a lot more effort to use mocks, and it can
# lead to tests that are harder to read. On the other hand, imagine
# if our app was more complex, and there were several more layers
# between the outside and the inside. Imagine leaving three or four
# or five layers of tests, all failing while we wait to get to the
# bottom layer to imple‐ ment our critical feature. While tests are
# failing, we’re not sure that layer really works, on its own terms,
# or not. We have to wait until we get to the bottom layer.

# This is a decision point you’re likely to run into in your own
# projects. Let’s investigate both approaches. We’ll start by taking
# the shortcut, and leaving the test failing. In the next chapter,
# we’ll come back to this exact point, and investigate how things
# would have gone if we’d used more isolation.


# One of the benefits of integrated tests is that they help you to
# catch less predictable interactions like this. We’d forgotten to
# write a test for the case where the user is not authenticated, but
# because the integrated tests use the stack all the way down, errors
# from the model layer came up to let us know we’d forgotten something

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>To-Do lists</title>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/base.css">
</head>

<body>
    <div class="container">
        <nav class="navbar navbar-default" role="navigation">
            <div class="container-fluid">
                <a href="/" class="navbar-brand">Superlists</a>
                {% if user.email %}
                <ul class="nav navbar-nav navbar-left">
                    <li><a href="{% url 'my_lists' user.email %}">My lists</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="navbar-text">Logged in as {{ user.email }}</li>
                    <li>
                        <a href="{% url 'logout' %}">Log out</a>
                    </li>
                </ul>
                {% else %}
                <form class="navbar-form navbar-right" method="POST" action="{% url 'send_login_email' %}">
                    <span>Enter email to log in:</span>
                    <input class="form-control" name="email" type="text" />
                    {% csrf_token %}
                </form>
                {% endif %}
            </div>
        </nav>

        {% if messages %}
        <div class="row">
            <div class="col-md-8">
                {% for message in messages %}
                {% if message.level_tag == 'success' %}
                <div class="alert alert-success">{{ message }}</div>
                {% else %}
                <div class="alert alert-warning">{{ message }}</div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        {% endif %}

        <div class="row">
            <div class="col-md-6 col-md-offset-3 jumbotron">
                <div class="text-center">
                    <h1>{% block header_text%}{% endblock %}</h1>
                    {% block list_form %}
                    <form method="POST" action="{% block form_action %}{% endblock %}">
                        {{ form.text }}
                        {% csrf_token %}
                        {% if form.errors %}
                        <div class="form-group has-error">
                            <span class="help-block">{{ form.text.errors }}</span>
                        </div>
                        {% endif %}
                    </form>
                    {% endblock %}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                {% block table %}
                {% endblock %}
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                {% block extra_content %}
                {% endblock %}
            </div>
        </div>
    </div>

    <script src="/static/jquery-3.4.1.min.js"></script>
    <script src="/static/list.js"></script>

    <script>
        // Whenever you have some JavaScript that interacts with the 
        // DOM, it’s always good to wrap it in some “onload” 
        // boilerplate code to make sure that the page has fully 
        // loaded before it tries to do anything. Currently it works 
        // anyway, because we’ve placed the <script> tag right at the 
        // bottom of the page, but we shouldn’t rely on that.
        $(document).ready(function () {
            window.Superlists.initialize();
        });
    </script>

    <!-- 
        It’s good practice to put your script loads at the end of your body HTML, as it means the user doesn’t have to wait for all your JavaScript to load before they can see something on the page. It also helps to make sure most of the DOM has loaded before any scripts run.
    -->

</body>

</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new Your To-Do list{% endblock %}

{% block form_action %}{% url 'new_list' %}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block table %}
<table id="id_list_table" class="table">
    {% for item in list.item_set.all %}
    <!-- .item_set is called a reverse lookup. -->
    <!-- It's one of Django's incredibly useful bits of ORM -->
    <!-- that lets you look up an object's related items from -->
    <!-- a different table -->
    <tr>
        <td>{{ forloop.counter }}: {{ item.text }}</td>
    </tr>
    {% endfor %}
</table>

{% if list.owner %}
<p>List owner: <span id="id_list_owner">{{ list.owner.email }}</span></p>
{% endif %}
{% endblock %}

{% block extra_content %}
<div class="row">
    <div class="col-md-6">
        <h3>Shared with</h3>
        <ul>
            {% for sharee in list.shared_with.all %}
            <li class="list-sharee">{{ sharee.email }}</li>
            {% endfor %}
        </ul>
    </div>

    <div class="col-md-3">
        <h3>Share this list:</h3>
        <form class="form-inline" method="POST" action="{% url 'share_list' list.id %}">
            {% csrf_token %}
            <input name="sharee" placeholder="your-friend@example.com" />
        </form>
        <h3>Shared with</h3>
        <ul>
            {% for sharee in list.shared_with.all %}
            <li class="list-sharee">{{ sharee.email }}</li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

lists/templates/my_lists.html
{% extends 'base.html' %}

{% block header_text %}My Lists{% endblock %}

{% block list_form %}{% endblock %}

{% block extra_content %}
<h2>{{ owner.email }}'s lists</h2> <!-- 1 -->
<ul>
    {% for list in owner.list_set.all %}
    <!-- 2 -->
    <li><a href="{{ list.get_absolute_url }}">{{ list.name }}</a></li> <!-- 3 -->
    {% endfor %}
</ul>

<h2>Lists shared by other users</h2>
<ul>
    {% for list in owner.shared_lists.all %}
    <li>
        <a href="{{ list.get_absolute_url }}">{{ list.name }}</a>
        ({{ list.owner.email }})
    </li>
    {% endfor %}
</ul>
{% endblock %}

<!-- 
1. We want a variable called owner to represent the user in our 
    template.
2. We want to be able to iterate through the lists created by the 
    user using owner.list_set.all (I happen to know we get this for 
    free from the Django ORM).
3. We want to use list.name to print out the “name” of the list, 
    which is currently specified as the text of its first element.
-->